version: { build }
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
skip_branch_with_pr: true
environment:
  nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - npm install
build: off
test_script:
  - npm run test:ci
  - ps: |
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))
deploy_script:
  - IF "%APPVEYOR_REPO_TAG%"=="true" npm publish --access public
