version: 2.1.0-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
skip_branch_with_pr: true
environment:
  nodejs_version: "10"
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: '"//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII'
  - npm whoami
  - npm --loglevel=error install
build: off
test_script:
  - ps: |
      $failed = $FALSE
      npm run test:ci
      if (-not $?) { $failed = $TRUE }
      $wc = New-Object 'System.Net.WebClient'
      $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))
      if ($failed) { throw "The unit tests failed." }

deploy_script:
  - ps: |
      if ($env:publish_packages -eq "true")
      {
          npm version $env:APPVEYOR_BUILD_VERSION
          npm publish --access public
      }
